### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jayantanth** [tshrinivasan/tools-for-wiki#13]
Moving the file 4990010208747 - Sakuntala Tatwa, Basu, Chandra Nath, 172p, LANGUAGE. LINGUISTICS. LITERATURE, bengali (1881).pdf to the folder 'uploaded-2016-05-09-00-57-22'
Uploading the file 4990010208798 - Sarojini Natak Ed. 3, Thakur, Jyotirindranath, 198p, LANGUAGE. LINGUISTICS. LITERATURE, bengali (1881).pdf
Traceback (most recent call last):
  File "commons.py", line 142, in <module>
    upload_pdf_file(pdf_file)
  File "commons.py", line 134, in upload_pdf_file
    page.edit(text=wikidata)
  File "/usr/local/lib/python2.7/dist-packages/wikitools/page.py", line 623, in edit
    result = req.query()
  File "/usr/local/lib/python2.7/dist-packages/wikitools/api.py", line 158, in query
    rawdata = self.__getRaw()
  File "/usr/local/lib/python2.7/dist-packages/wikitools/api.py", line 265, in __getRaw
    data = self.opener.open(self.request)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>

**Comment by tshrinivasan** [comment]
This seems some issue with internet connection.

Is the issues happens every time?

**Comment by jayantanth** [comment]
The file was uploaded successfully after next run.

**Comment by jayantanth** [comment]
Proposal : Could you please add more logic about checking file name already exist ? If the file name exist at commons,  the script should try next file to upload.

**Comment by tshrinivasan** [comment]
Thats nice idea.

Will do it.

**Comment by jayantanth** [comment]
I have tried one for same name file to upload, found the error below.....

python commons.py
```
Logged in.
Uploading the file 4990010005040 - Government Gazette(January-December)1847, N. A., 817p, GENERALITIES, bengali (1847).pdf
Traceback (most recent call last):
  File "commons.py", line 142, in <module>
    upload_pdf_file(pdf_file)
  File "commons.py", line 84, in upload_pdf_file
    pdf.upload(fileobj=file_object,comment=caption, ignorewarnings=True)
  File "/usr/local/lib/python2.7/dist-packages/wikitools/wikifile.py", line 240, in upload
    res = req.query()
  File "/usr/local/lib/python2.7/dist-packages/wikitools/api.py", line 165, in query
    raise APIError(data['error']['code'], data['error']['info'])
wikitools.api.APIError: (u'fileexists-shared-forbidden', u'A file with name "\u0997\u09ac\u09b0\u09cd\u09a3\u09ae\u09c7\u09a3\u09cd\u099f\u09cd\u200c_\u0997\u09c7\u099c\u09c7\u099f\u09cd\u200c_(\u099c\u09be\u09a8\u09c1\u09af\u09bc\u09be\u09b0\u09bf-\u09a1\u09bf\u09b8\u09c7\u09ae\u09cd\u09ac\u09b0)_\u09e7\u09ee\u09ea\u09ed.pdf" already exists in the shared file repository, and cannot be overwritten.')
```
